name: habit_tracker
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^14.6.3
  flutter_svg: ^2.0.17
  intl: ^0.20.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  form_inputs:
    path: packages/form_inputs
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  database_client:
    path: packages/database_client
  habit_repository:
    path: packages/habit_repository
  formz: ^0.8.0
  firebase_core: ^3.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300

